version: 2
jobs: 
  bobby: 
    docker:
      - image: circleci/ruby:2.4.1
    steps: 
      - checkout
      - run: echo "A first Hello!"
  sally: 
    docker:
      - image: circleci/ruby:2.4.1
    steps: 
      - checkout
      - run: echo "Dobule trobule!"
workflows: 
  version: 2
  bobby_sally:
    jobs:
      - bobby
      - sally