version: 2
jobs:
  build:
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout # check out the code in the project directory
      - run: echo "npm installing..." # run the `echo` command
      - run: npm install
      - run: CI=true npm run build
  test:
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout # check out the code in the project directory
      - run: echo "testing..." # run the `echo` command
      - run: npm install
      - run: npm test
  hithere:
    docker:
      - image: cimg/node:16.13.2
    steps:
      - checkout # check out the code in the project directory
      - run: echo "helllllllo!" # run the `echo` command

workflows:
  version: 2
  build_test_lint:
    jobs:
      - build
      - hithere
      - test:
          requires:
            - hithere
